name: Site Build & Deploy

on: [push]

jobs:
  Tarball:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - uses: actions/cache@v1
      id: cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
      
    - name: Install Bundler
      run: |
        gem install bundler -v '2.0.2'
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        bundle install --deployment
    - name: Build
      run: |
        JEKYLL_ENV=production
        bundle exec jekyll build --destination site
    - name: Deploy
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Github Actions Deploy"
        cd site
        git init
        git add .
        git commit --quiet -m ":rocket: Deploy to Github Pages"
        git push --force --quiet "https://nmcardoso:${{ secrets.ACTIONS_TOKEN }}@github.com/nmcardoso/splus-website.git" master:gh-pages
#     - name: Prepare Files
#       run: |
#         chmod +x -R ci_scripts/
#         echo $ACTIONS_TOKEN
#     - name: Build Script
#       run: ./ci_scripts/build.sh
#     - name: Deploy Script
#       env:
#         ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
#       run: ./ci_scripts/deploy.sh
